{% set version = '1.8-14' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rserve
  version: {{ version|replace("-", "_") }}

source:
  url: 
    - https://www.rforge.net/src/contrib/Rserve_{{ version }}.tar.gz
    - https://www.rforge.net/Rserve/snapshot/Rserve_{{ version }}.tar.gz
  sha256: cf3923f32b1b548000d68c35840bc9a9a2a7c43a5543b273cd714d1cc24938c0

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libblas                      # [linux]
    - libxcrypt                    # [linux]
    - openssl
  run:
    - r-base

test:
  commands:
    - $R -e "library('Rserve')"           # [not win]
    - "\"%R%\" -e \"library('Rserve')\""  # [win]

about:
  home: https://www.rforge.net/Rserve/
  dev_url: https://github.com/s-u/Rserve
  license: GPL-2.0-only
  summary: Rserve acts as a socket server (TCP/IP or local sockets)  which allows binary requests
    to be sent to R. Every connection has a separate workspace and working directory.
    Client-side implementations are available for popular languages such as C/C++ and
    Java, allowing any application to use facilities of R without the need of linking
    to R code. Rserve supports remote connection, user authentication and file transfer.
    A simple R client is included in this package as well.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1
