{% set version = '1.8-7' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rserve
  version: {{ version|replace("-", "_") }}

source:
  url: http://www.rforge.net/Rserve/snapshot/Rserve_{{ version }}.tar.gz
  sha256: cf3923f32b1b548000d68c35840bc9a9a2a7c43a5543b273cd714d1cc24938c0

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libiconv                   # [osx]
    - libblas                    # [linux]
    - openssl
  run:
    - r-base
    - libiconv                   # [osx]
    - libblas                    # [linux]
    - openssl

test:
  commands:
    - $R -e "library('Rserve')"           # [not win]
    - "\"%R%\" -e \"library('Rserve')\""  # [win]

about:
  home: http://www.rforge.net/Rserve/
  license: GPL-2.0-only
  summary: Rserve acts as a socket server (TCP/IP or local sockets)  which allows binary requests
    to be sent to R. Every connection has a separate workspace and working directory.
    Client-side implementations are available for popular languages such as C/C++ and
    Java, allowing any application to use facilities of R without the need of linking
    to R code. Rserve supports remote connection, user authentication and file transfer.
    A simple R client is included in this package as well.
  license_family: GPL2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1

# Package: Rserve
# Version: 1.7-3.1
# Title: Binary R server
# Author: Simon Urbanek <Simon.Urbanek@r-project.org>
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: R (>= 1.5.0)
# Suggests: RSclient
# SystemRequirements: libR, GNU make
# Description: Rserve acts as a socket server (TCP/IP or local sockets)  which allows binary requests to be sent to R. Every connection has a separate workspace and working directory. Client-side implementations are available for popular languages such as C/C++ and Java, allowing any application to use facilities of R without the need of linking to R code. Rserve supports remote connection, user authentication and file transfer. A simple R client is included in this package as well.
# License: GPL-2 | file LICENSE
# URL: http://www.rforge.net/Rserve/
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-04-15 16:53:44 UTC
# Packaged: 2019-03-14 18:24:52 UTC; ripley
