appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AUZQvl+sOFKCUFRhVgaEfJo6CrmDmny31ah+a7QcR465uN3RYulDnNckMvpgqvWSpIrRfDStFU743vz4ff3CyvK52FxjOpChaYUrhXi4GQmj18LMQqWCufaXptHDRhkO5xSOF7NYkMmPeAFgxV2VKPb726aVcAeJHsco4BXn7Jie1voKFaLeHQ7mu+SEBUgXF+jvBVo/KW5bBynYvtjZsuRsvREC67+210CIk3LRBdcPMPuSP0wcUH7MS6iBrFf3PpUJ+aUoFGSSdYctQZsJTaTLM9q4spK1Gs0Be16wntxP7hq96sXepiJjNyav+8M/kA3Wtb9HPbS9BLvmOJcEIvcugOPOrb9gMvU3LfR7/3MXbQtSF52sYa5HTqK+FNDBCppfdV1KMK67DoUyu3tgB39hkRSsh8Mr7hpd2YgBUjUvmmk+1OuXS5IuPEndHNnLveLBeoyo3CsanrAvZfhWlHBzMBmnRhk8SOdFLyyGJKVQCa+MKlunUhEsDKSy3/mTFYz2rhryqC1dXypqkz7JwHPVMNp+ykaSAf09vrSJUwDbPio8rEM+IA2/mku8pnP3hrgX67BmlsXK6JxMiYUH9l2BhBnBXR0lEivzBVE3MzdGES8u5V5hgPATKXdohpJaJV7wUqOwfU6Yx0XHJH4QBeBxof1nvL/OMhYjpDbZL2Y=
conda_forge_output_validation: false
